name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.13.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - lib/images/logo_blanco.jpg
    - lib/images/logo_negro.jpg
  uses-material-design: true

  flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/images/Logo_mobile.png"